Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 4
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	72	verify_vars
	73
Select jobs to execute...

[Wed Dec  2 15:34:51 2020]
rule verify_vars:
    input: data/remapped_vars/ENSSSCG00000002756.remapped
    output: data/verified_vars/ENSSSCG00000002756.verified
    jobid: 354
    wildcards: id=ENSSSCG00000002756

[Wed Dec  2 15:34:51 2020]
rule verify_vars:
    input: data/remapped_vars/ENSSSCG00000020924.remapped
    output: data/verified_vars/ENSSSCG00000020924.verified
    jobid: 324
    wildcards: id=ENSSSCG00000020924

[Wed Dec  2 15:34:51 2020]
rule verify_vars:
    input: data/remapped_vars/ENSSSCG00000003141.remapped
    output: data/verified_vars/ENSSSCG00000003141.verified
    jobid: 349
    wildcards: id=ENSSSCG00000003141

[Wed Dec  2 15:34:51 2020]
rule verify_vars:
    input: data/remapped_vars/ENSSSCG00000015616.remapped
    output: data/verified_vars/ENSSSCG00000015616.verified
    jobid: 346
    wildcards: id=ENSSSCG00000015616

[Wed Dec  2 15:34:53 2020]
Error in rule verify_vars:
    jobid: 354
    output: data/verified_vars/ENSSSCG00000002756.verified

RuleException:
CalledProcessError in line 41 of /home/pelmo/sscrofa_variant_remapping/Snakefile:
Command 'set -euo pipefail;  /home/pelmo/anaconda3/envs/snakemake/bin/python3.9 /home/pelmo/sscrofa_variant_remapping/.snakemake/scripts/tmph3zkj64_.var_confirmation.py' returned non-zero exit status 1.
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2273, in run_wrapper
  File "/home/pelmo/sscrofa_variant_remapping/Snakefile", line 41, in __rule_verify_vars
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 560, in _callback
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 546, in cached_or_run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2304, in run_wrapper
[Wed Dec  2 15:34:58 2020]
Finished job 324.
1 of 73 steps (1%) done
Terminating processes on user request, this might take some time.
[Wed Dec  2 15:35:05 2020]
Error in rule verify_vars:
    jobid: 349
    output: data/verified_vars/ENSSSCG00000003141.verified

RuleException:
CalledProcessError in line 41 of /home/pelmo/sscrofa_variant_remapping/Snakefile:
Command 'set -euo pipefail;  /home/pelmo/anaconda3/envs/snakemake/bin/python3.9 /home/pelmo/sscrofa_variant_remapping/.snakemake/scripts/tmp7dc3uq6t.var_confirmation.py' died with <Signals.SIGINT: 2>.
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2273, in run_wrapper
  File "/home/pelmo/sscrofa_variant_remapping/Snakefile", line 41, in __rule_verify_vars
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 560, in _callback
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 546, in cached_or_run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2304, in run_wrapper
[Wed Dec  2 15:35:05 2020]
Error in rule verify_vars:
    jobid: 346
    output: data/verified_vars/ENSSSCG00000015616.verified

RuleException:
CalledProcessError in line 41 of /home/pelmo/sscrofa_variant_remapping/Snakefile:
Command 'set -euo pipefail;  /home/pelmo/anaconda3/envs/snakemake/bin/python3.9 /home/pelmo/sscrofa_variant_remapping/.snakemake/scripts/tmp_bjumyv7.var_confirmation.py' died with <Signals.SIGINT: 2>.
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2273, in run_wrapper
  File "/home/pelmo/sscrofa_variant_remapping/Snakefile", line 41, in __rule_verify_vars
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 560, in _callback
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 546, in cached_or_run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2304, in run_wrapper
Complete log: /home/pelmo/sscrofa_variant_remapping/.snakemake/log/2020-12-02T153451.315203.snakemake.log
